export interface PhetSimulation {
  title: string;
  slug: string;
}

export const PHET_SIMULATIONS: PhetSimulation[] = [
  { "title": "Membrane Transport", "slug": "membrane-transport" },
  { "title": "Quantum Coin Toss", "slug": "quantum-coin-toss" },
  { "title": "Number Pairs", "slug": "number-pairs" },
  { "title": "Quantum Measurement", "slug": "quantum-measurement" },
  { "title": "Models of the Hydrogen Atom", "slug": "models-of-the-hydrogen-atom" },
  { "title": "Buoyancy: Basics", "slug": "buoyancy-basics" },
  { "title": "Buoyancy", "slug": "buoyancy" },
  { "title": "Mean: Share and Balance", "slug": "mean-share-and-balance" },
  { "title": "Generator", "slug": "generator" },
  { "title": "Magnets and Electromagnets", "slug": "magnets-and-electromagnets" },
  { "title": "Magnet and Compass", "slug": "magnet-and-compass" },
  { "title": "Faraday's Electromagnetic Lab", "slug": "faradays-electromagnetic-lab" },
  { "title": "Projectile Sampling Distributions", "slug": "projectile-sampling-distributions" },
  { "title": "Projectile Data Lab", "slug": "projectile-data-lab" },
  { "title": "Center and Variability", "slug": "center-and-variability" },
  { "title": "Build a Nucleus", "slug": "build-a-nucleus" },
  { "title": "Kepler's Laws", "slug": "keplers-laws" },
  { "title": "Sound Waves", "slug": "sound-waves" },
  { "title": "Quadrilateral", "slug": "quadrilateral" },
  { "title": "My Solar System", "slug": "my-solar-system" },
  { "title": "Calculus Grapher", "slug": "calculus-grapher" },
  { "title": "Number Compare", "slug": "number-compare" },
  { "title": "Number Play", "slug": "number-play" },
  { "title": "Greenhouse Effect", "slug": "greenhouse-effect" },
  { "title": "Geometric Optics: Basics", "slug": "geometric-optics-basics" },
  { "title": "Geometric Optics", "slug": "geometric-optics" },
  { "title": "Density", "slug": "density" },
  { "title": "Circuit Construction Kit: AC", "slug": "circuit-construction-kit-ac" },
  { "title": "Circuit Construction Kit: AC - Virtual Lab", "slug": "circuit-construction-kit-ac-virtual-lab" },
  { "title": "Normal Modes", "slug": "normal-modes" },
  { "title": "Fourier: Making Waves", "slug": "fourier-making-waves" },
  { "title": "Number Line: Distance", "slug": "number-line-distance" },
  { "title": "Ratio and Proportion", "slug": "ratio-and-proportion" },
  { "title": "Collision Lab", "slug": "collision-lab" },
  { "title": "Number Line: Operations", "slug": "number-line-operations" },
  { "title": "Energy Skate Park", "slug": "energy-skate-park" },
  { "title": "Build a Molecule", "slug": "build-a-molecule" },
  { "title": "Natural Selection", "slug": "natural-selection" },
  { "title": "Number Line: Integers", "slug": "number-line-integers" },
  { "title": "Vector Addition: Equations", "slug": "vector-addition-equations" },
  { "title": "Vector Addition", "slug": "vector-addition" },
  { "title": "Curve Fitting", "slug": "curve-fitting" },
  { "title": "Gravity Force Lab: Basics", "slug": "gravity-force-lab-basics" },
  { "title": "Waves Intro", "slug": "waves-intro" },
  { "title": "Diffusion", "slug": "diffusion" },
  { "title": "Gases Intro", "slug": "gases-intro" },
  { "title": "Gas Properties", "slug": "gas-properties" },
  { "title": "Blackbody Spectrum", "slug": "blackbody-spectrum" },
  { "title": "Masses and Springs: Basics", "slug": "masses-and-springs-basics" },
  { "title": "Energy Forms and Changes", "slug": "energy-forms-and-changes" },
  { "title": "Wave Interference", "slug": "wave-interference" },
  { "title": "Fractions: Mixed Numbers", "slug": "fractions-mixed-numbers" },
  { "title": "Fractions: Intro", "slug": "fractions-intro" },
  { "title": "Build a Fraction", "slug": "build-a-fraction" },
  { "title": "Fractions: Equality", "slug": "fractions-equality" },
  { "title": "Coulomb's Law", "slug": "coulombs-law" },
  { "title": "Graphing Quadratics", "slug": "graphing-quadratics" },
  { "title": "Masses and Springs", "slug": "masses-and-springs" },
  { "title": "Equality Explorer: Two Variables", "slug": "equality-explorer-two-variables" },
  { "title": "Equality Explorer: Basics", "slug": "equality-explorer-basics" },
  { "title": "Equality Explorer", "slug": "equality-explorer" },
  { "title": "Area Model Algebra", "slug": "area-model-algebra" },
  { "title": "Area Model Decimals", "slug": "area-model-decimals" },
  { "title": "Area Model Multiplication", "slug": "area-model-multiplication" },
  { "title": "Area Model Introduction", "slug": "area-model-introduction" },
  { "title": "Gene Expression Essentials", "slug": "gene-expression-essentials" },
  { "title": "Capacitor Lab: Basics", "slug": "capacitor-lab-basics" },
  { "title": "Circuit Construction Kit: DC - Virtual Lab", "slug": "circuit-construction-kit-dc-virtual-lab" },
  { "title": "Circuit Construction Kit: DC", "slug": "circuit-construction-kit-dc" },
  { "title": "Pendulum Lab", "slug": "pendulum-lab" },
  { "title": "Projectile Motion", "slug": "projectile-motion" },
  { "title": "Molecule Polarity", "slug": "molecule-polarity" },
  { "title": "Expression Exchange", "slug": "expression-exchange" },
  { "title": "Graphing Slope-Intercept", "slug": "graphing-slope-intercept" },
  { "title": "Function Builder: Basics", "slug": "function-builder-basics" },
  { "title": "Proportion Playground", "slug": "proportion-playground" },
  { "title": "Unit Rates", "slug": "unit-rates" },
  { "title": "Make a Ten", "slug": "make-a-ten" },
  { "title": "States of Matter: Basics", "slug": "states-of-matter-basics" },
  { "title": "States of Matter", "slug": "states-of-matter" },
  { "title": "Gravity and Orbits", "slug": "gravity-and-orbits" },
  { "title": "Plinko Probability", "slug": "plinko-probability" },
  { "title": "Atomic Interactions", "slug": "atomic-interactions" },
  { "title": "Charges and Fields", "slug": "charges-and-fields" },
  { "title": "Rutherford Scattering", "slug": "rutherford-scattering" },
  { "title": "Function Builder", "slug": "function-builder" },
  { "title": "Isotopes and Atomic Mass", "slug": "isotopes-and-atomic-mass" },
  { "title": "Neuron", "slug": "neuron" },
  { "title": "Trig Tour", "slug": "trig-tour" },
  { "title": "Bending Light", "slug": "bending-light" },
  { "title": "Arithmetic", "slug": "arithmetic" },
  { "title": "Hooke's Law", "slug": "hookes-law" },
  { "title": "Molecules and Light", "slug": "molecules-and-light" },
  { "title": "Least-Squares Regression", "slug": "least-squares-regression" },
  { "title": "Molecule Shapes", "slug": "molecule-shapes" },
  { "title": "Molecule Shapes: Basics", "slug": "molecule-shapes-basics" },
  { "title": "Reactants, Products and Leftovers", "slug": "reactants-products-and-leftovers" },
  { "title": "Energy Skate Park: Basics", "slug": "energy-skate-park-basics" },
  { "title": "Faraday's Law", "slug": "faradays-law" },
  { "title": "pH Scale: Basics", "slug": "ph-scale-basics" },
  { "title": "Area Builder", "slug": "area-builder" },
  { "title": "Wave on a String", "slug": "wave-on-a-string" },
  { "title": "Color Vision", "slug": "color-vision" },
  { "title": "Graphing Lines", "slug": "graphing-lines" },
  { "title": "Fraction Matcher", "slug": "fraction-matcher" },
  { "title": "Balancing Act", "slug": "balancing-act" },
  { "title": "Acid-Base Solutions", "slug": "acid-base-solutions" },
  { "title": "Under Pressure", "slug": "under-pressure" },
  { "title": "Friction", "slug": "friction" },
  { "title": "Forces and Motion: Basics", "slug": "forces-and-motion-basics" },
  { "title": "John Travoltage", "slug": "john-travoltage" },
  { "title": "Concentration", "slug": "concentration" },
  { "title": "Gravity Force Lab", "slug": "gravity-force-lab" },
  { "title": "Balloons and Static Electricity", "slug": "balloons-and-static-electricity" },
  { "title": "Beer's Law Lab", "slug": "beers-law-lab" },
  { "title": "Molarity", "slug": "molarity" },
  { "title": "Ohm's Law", "slug": "ohms-law" },
  { "title": "Resistance in a Wire", "slug": "resistance-in-a-wire" },
  { "title": "Build an Atom", "slug": "build-an-atom" }
];
